[2023-11-03T11:12:45.310+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movies-etl-dag.write_to_es manual__2023-11-03T11:12:34.997564+00:00 [queued]>
[2023-11-03T11:12:45.318+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movies-etl-dag.write_to_es manual__2023-11-03T11:12:34.997564+00:00 [queued]>
[2023-11-03T11:12:45.318+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-11-03T11:12:45.334+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): write_to_es> on 2023-11-03 11:12:34.997564+00:00
[2023-11-03T11:12:45.342+0000] {standard_task_runner.py:57} INFO - Started process 823 to run task
[2023-11-03T11:12:45.346+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movies-etl-dag', 'write_to_es', 'manual__2023-11-03T11:12:34.997564+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/movie_pg_es.py', '--cfg-path', '/tmp/tmpnpnjax4v']
[2023-11-03T11:12:45.349+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask write_to_es
[2023-11-03T11:12:45.516+0000] {task_command.py:415} INFO - Running <TaskInstance: movies-etl-dag.write_to_es manual__2023-11-03T11:12:34.997564+00:00 [running]> on host e468bf2dfd15
[2023-11-03T11:12:45.765+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movies-etl-dag' AIRFLOW_CTX_TASK_ID='write_to_es' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T11:12:34.997564+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-03T11:12:34.997564+00:00'
[2023-11-03T11:12:45.829+0000] {movie_pg_es.py:113} INFO - Processing 2 movie:
[2023-11-03T11:12:45.830+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/movie_pg_es.py", line 114, in write_to_es
    actions = [
  File "/opt/airflow/dags/movie_pg_es.py", line 116, in <listcomp>
    _index=MOVIES_ES_INDEX, _id=film_data.id, _source=film_data.dict()
AttributeError: 'str' object has no attribute 'id'
[2023-11-03T11:12:45.885+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=movies-etl-dag, task_id=write_to_es, execution_date=20231103T111234, start_date=20231103T111245, end_date=20231103T111245
[2023-11-03T11:12:45.902+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 72 for task write_to_es ('str' object has no attribute 'id'; 823)
[2023-11-03T11:12:45.920+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-03T11:12:45.992+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
